# Makefile
# 
# Converts Markdown to other formats (HTML, PDF, DOCX, RTF, ODT, EPUB) using Pandoc
# <http://johnmacfarlane.net/pandoc/>
#
# Run "make" (or "make all") to convert to all other formats
#
# Run "make clean" to delete converted files

# Convert all files in this directory that have a .md suffix
SOURCE_DOCS := $(wildcard *.md)


EXPORTED_DOCS=$(SOURCE_DOCS:.md=.pdf)

#EXPORTED_DOCS=\
# $(SOURCE_DOCS:.md=.html) \
# $(SOURCE_DOCS:.md=.pdf) \
# $(SOURCE_DOCS:.md=.docx) \
# $(SOURCE_DOCS:.md=.rtf) \
# $(SOURCE_DOCS:.md=.odt) \
# $(SOURCE_DOCS:.md=.epub)

RM=/bin/rm

# Get the current user ID to use for docker run and docker exec commands
DOCKER_UID           = $(shell id -u)
DOCKER_GID           = $(shell id -g)
DOCKER_USER          = $(DOCKER_UID):$(DOCKER_GID)
CURRENT_DIR := $(dir $(abspath $(firstword $(MAKEFILE_LIST))))


# make ARCH_WITH_MD_EXTENSION.pdf USE_DOCKER=no
USE_DOCKER=no


EXT := ".exe"
OS := $(shell uname)
ifeq ($(OS), Darwin)
# Run MacOS commands 
	EXT := ""
endif
ifeq ($(OS), Linux)
# Run Linux commands 
	EXT := ""
endif
EXT := ".exe"



#ifdef USE_DOCKER
ifeq ($(USE_DOCKER),yes)
	PANDOC := docker run --rm --volume "$(CURRENT_DIR):/data" --user $(DOCKER_USER) pandoc-texlive-full-jz
else
	PANDOC := pandoc$(EXT)
endif


#$(info PANDOC extension is $(UNAME) )

PANDOC_OPTIONS=--standalone -f markdown+pipe_tables+backtick_code_blocks+auto_identifiers+strikeout+yaml_metadata_block+implicit_figures+all_symbols_escapable+link_attributes+smart+fenced_divs
PANDOC_HTML_OPTIONS=--to html5
PANDOC_PDF_OPTIONS=
PANDOC_XELATEX_PDF_OPTIONS=--dpi=300 --slide-level 2 --toc --citeproc --listings --shift-heading-level=0 --data-dir=./pandoc --template templates/default_mod.latex -H pandoc/templates/preamble.tex --pdf-engine lualatex -V classoption:aspectratio=169 -V classoption:t -t beamer
PANDOC_DOCX_OPTIONS=
PANDOC_RTF_OPTIONS=
PANDOC_ODT_OPTIONS=
PANDOC_EPUB_OPTIONS=--to epub3


# Pattern-matching Rules

%.html : %.md
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_HTML_OPTIONS) -o $@ $<

%.pdf : %.md
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_XELATEX_PDF_OPTIONS) -o $@ $<
	
%.docx : %.md
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_DOCX_OPTIONS) -o $@ $<

%.rtf : %.md
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_RTF_OPTIONS) -o $@ $<

%.odt : %.md
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_ODT_OPTIONS) -o $@ $<

%.epub : %.md
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_EPUB_OPTIONS) -o $@ $<


# Targets and dependencies

.PHONY: all clean

all : $(EXPORTED_DOCS)



clean:
	- $(RM) $(EXPORTED_DOCS)




